20 Basic Numpy Exercises - From Array Creation to making an array Immutable

In [0]:
import numpy as np

1. Check your version

In [2]:
np.__version__

'1.18.4'

2. Create a 3x3 Array filled with zeroes

In [3]:
arr_0 = np.zeros((3,3))
arr_0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Create a 3x3 Array filled with the number 7

In [4]:
arr_7 = np.full((3,3),7)
arr_7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

4. Create a vector of at least size 5 filled with Random Values between -1 and 1

In [5]:
v = np.random.uniform(-1,1,(1,5))
v

array([[-0.32704603,  0.64496337, -0.09797937, -0.49406484,  0.60073107]])

5. Multiply the two matricies (A and B) below.  (Assign the answer to the variable ANS) - Run the cell below to check your answer

In [0]:
A = np.array([[.15,.55,.7]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [0]:
ans = np.dot(A,B)

In [8]:
# Checking the answer!
assert np.sum(ans) == 25.95,'Try again'
print('Good job!', ans)

Good job! [[ 7.25  8.65 10.05]]


6. Combine the [ans] array created in #5 with the following 2 arrays below.

In [0]:
first_row = np.array([[0.1, 0.1, 9.9]])
last_row = np.array([[9.9, 9.9, 0.1]])

In [10]:
new_ans = np.vstack((first_row, ans ,last_row))
new_ans

array([[ 0.1 ,  0.1 ,  9.9 ],
       [ 7.25,  8.65, 10.05],
       [ 9.9 ,  9.9 ,  0.1 ]])

In [11]:
new_ans = np.concatenate((first_row, ans ,last_row),axis=0)
new_ans

array([[ 0.1 ,  0.1 ,  9.9 ],
       [ 7.25,  8.65, 10.05],
       [ 9.9 ,  9.9 ,  0.1 ]])

7. Swap the first and last columns in the combined array.

In [12]:
swapped_ans = np.concatenate(
    (new_ans[:,2].reshape(3,1),new_ans[:,1].reshape(3,1),new_ans[:,0].reshape(3,1)),axis=1)
swapped_ans

array([[ 9.9 ,  0.1 ,  0.1 ],
       [10.05,  8.65,  7.25],
       [ 0.1 ,  9.9 ,  9.9 ]])

8. Swap the first and the middle row in the combined array

In [13]:
row_swap = np.vstack((swapped_ans[1,:],swapped_ans[0,:],swapped_ans[2,:]))
row_swap

array([[10.05,  8.65,  7.25],
       [ 9.9 ,  0.1 ,  0.1 ],
       [ 0.1 ,  9.9 ,  9.9 ]])

9. Save the combined array from #8 to file.

In [0]:
np.savetxt('my_txt_array.txt', row_swap, delimiter=' ')

In [0]:
np.savetxt('my_csv_array.csv', row_swap, delimiter=',')

10. Load the saved array from file into a new array.

In [16]:
load_txt = np.loadtxt('my_txt_array.txt')
load_txt

array([[10.05,  8.65,  7.25],
       [ 9.9 ,  0.1 ,  0.1 ],
       [ 0.1 ,  9.9 ,  9.9 ]])

In [17]:
load_csv = np.genfromtxt('my_csv_array.csv', delimiter=',')
load_csv

array([[10.05,  8.65,  7.25],
       [ 9.9 ,  0.1 ,  0.1 ],
       [ 0.1 ,  9.9 ,  9.9 ]])

11. Convert all array elements to float32

In [0]:
fp32_arr = row_swap.astype(np.float32)

12. Find the mean of the middle row of the following array.

In [19]:
# For Questions 12-19 use the following array
arr = np.random.randint(1,10,(7,7))
arr

array([[3, 6, 8, 3, 9, 5, 3],
       [8, 6, 8, 6, 7, 7, 9],
       [7, 4, 6, 8, 9, 5, 1],
       [1, 2, 2, 1, 9, 4, 2],
       [8, 9, 2, 1, 4, 3, 4],
       [8, 7, 3, 6, 8, 7, 3],
       [4, 2, 1, 6, 4, 8, 6]])

In [20]:
arr[len(arr)//2,:].mean()

3.0

13. Find the Variance of the array.

In [21]:
arr.var()

6.789670970428988

14. Slice the array into a new array of just it's middle column.

In [22]:
arr[:,len(arr[0])//2]
# If you need it to still be the same shape, you would want to reshape it with
# .reshape(len(arr[0]),1)

array([3, 6, 8, 1, 1, 6, 6])

15. Create a new Array of all the elements on the left to right, top to bottom, diagnal.

In [23]:
np.diag(arr)

array([3, 6, 6, 1, 4, 7, 6])

16. Find the most frequently occuring value in the array.

In [24]:
np.argmax(np.bincount(arr.flatten()))

8

17. Normalize the array

In [25]:
norm_arr = arr / np.max(arr)
norm_arr

array([[0.33333333, 0.66666667, 0.88888889, 0.33333333, 1.        ,
        0.55555556, 0.33333333],
       [0.88888889, 0.66666667, 0.88888889, 0.66666667, 0.77777778,
        0.77777778, 1.        ],
       [0.77777778, 0.44444444, 0.66666667, 0.88888889, 1.        ,
        0.55555556, 0.11111111],
       [0.11111111, 0.22222222, 0.22222222, 0.11111111, 1.        ,
        0.44444444, 0.22222222],
       [0.88888889, 1.        , 0.22222222, 0.11111111, 0.44444444,
        0.33333333, 0.44444444],
       [0.88888889, 0.77777778, 0.33333333, 0.66666667, 0.88888889,
        0.77777778, 0.33333333],
       [0.44444444, 0.22222222, 0.11111111, 0.66666667, 0.44444444,
        0.88888889, 0.66666667]])

18. Round the normalized array down to the nearest int.

In [26]:
np.floor(norm_arr)

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

19. Make the array Unmutable

In [0]:
norm_arr.flags.writeable = False

20. What do you get when you multiply the following arrays `[True, True, False] * [False, False, True]`?

In [28]:
arr = np.array([1,1,0])
f_arr = arr == 1
s_arr = arr < 1
print(f_arr, s_arr)
print()
print(f_arr * s_arr)

[ True  True False] [False False  True]

[False False False]
